# Generated by Django 6.0.4 on 2026-04-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="due_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
