# Generated by Django 5.2 on 2026-04-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Staff', 'Staff'), ('Supervisor', 'Supervisor')], max_length=100),
        ),
    ]
